<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CustomExceptions\" />
    <Folder Include="Mapping\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle" Version="1.8.9" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.5.1" />
    <PackageReference Include="BouncyCastle.NetCore" Version="2.2.1" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.1.0" />
    <PackageReference Include="itext7" Version="9.1.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.1.0" />
    <PackageReference Include="itext7.bouncy-castle-fips-adapter" Version="9.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
    <PackageReference Include="System.Text.Json" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NorthwindTraders.Domain\NorthwindTraders.Domain.csproj" />
  </ItemGroup>

</Project>
